basePath: /
definitions:
  models.Workshop:
    properties:
      address:
        type: string
      id:
        type: string
      name:
        type: string
    type: object
info:
  contact: {}
  description: API de microservicio para gestión de workshops
  title: Workshop API
  version: "1.0"
paths:
  /health:
    get:
      description: Retorna un mensaje que indica que el microservicio está en funcionamiento
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Verifica el estado del microservicio
      tags:
      - Health
  /workshops:
    get:
      description: Devuelve una lista JSON con todos los Workshops existentes en la
        base de datos
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Workshop'
            type: array
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Obtiene todos los Workshops
      tags:
      - Workshops
swagger: "2.0"
